### ISSUE TITLE
Chapter 3.15  - Unknown value (<$>)

### ISSUE THREAD

**Issue by SamHowie** [paf31/purescript-book-sources#26] opened 2015-10-04 23:58 UTC
In chapter 3.15 we execute the following in the psci REPL:

    showEntry <$> findEntry "John" "Smith" emptyBook

Instead of outputting:

    Nothing

It outputs the error:
```
Error:
Error in module $PSCI:
Error in value declaration main:
No instance found for $PSCI.Support.Eval (Data.Maybe.Maybe Data.AddressBook.Entry<>)
See https://github.com/purescript/purescript/wiki/Error-Code-NoInstanceFound for more information, or to contribute content related to this error.
```

What could be going on?

**Comment by paf31** [comment] 2015-10-05 16:21
This one works for me:

```
$ pulp psci

> import Prelude
> import Data.AddressBook 
> showEntry <$> findEntry "John" "Smith" emptyBook
Nothing
```

**Comment by SamHowie** [comment] 2015-10-05 20:35
Ah. I see my error. I had not imported Prelude.

Maybe the snippet in the book could change from:

```
$ pulp psci

> import Data.AddressBook 
```

to:

```
$ pulp psci

> import Prelude
> import Data.AddressBook 
```

I guess Prelude is essentially a standard library?

**Comment by benlambt** [comment] 2016-02-20 16:17
The problem is that the example in 3.15 of the book omits the `import Prelude` part.

**Comment by paf31** [comment] 2016-07-03 21:26
This will be fixed in the next release, thanks!

**Closed by paf31** 2016-07-03 21:26 UTC
